# Generated by ChatGPT for Django 4.2 compatibility

import django.core.validators
from django.db import migrations, models


USERNAME_VALIDATOR = django.core.validators.RegexValidator(
    regex=r'^[\w.@+-]+$',
    message='Username may contain letters, numbers, and @/./+/-/_ characters only.',
)


def populate_usernames(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    used = set()
    for user in User.objects.all().order_by('pk'):
        base = ''
        if getattr(user, 'email', ''):
            base = user.email.split('@')[0]
        base = base or f'user{user.pk}'
        base = ''.join(ch if ch.isalnum() or ch in '._+-@' else '_' for ch in base).strip('._+-@') or f'user{user.pk}'
        candidate = base[:150]
        counter = 1
        while candidate.lower() in used or User.objects.filter(username__iexact=candidate).exclude(pk=user.pk).exists():
            suffix = f'_{counter}'
            candidate = f'{base[:150-len(suffix)]}{suffix}'
            counter += 1
        user.username = candidate
        user.save(update_fields=['username'])
        used.add(candidate.lower())


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(
                max_length=150,
                null=True,
                blank=True,
                validators=[USERNAME_VALIDATOR],
            ),
        ),
        migrations.RunPython(populate_usernames, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[USERNAME_VALIDATOR],
            ),
        ),
    ]
