# Generated by Django 6.0.4 on 2026-06-18 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coach', '0001_initial'),
        ('gym_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalfeedback',
            name='activity_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_feedbacks', to='gym_user.activitylog'),
        ),
        migrations.AddField(
            model_name='professionalfeedback',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='coach.coach'),
        ),
        migrations.AddField(
            model_name='professionalfeedback',
            name='gym_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_feedbacks', to='gym_user.gymuser'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='coach.workout'),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='coach.coach'),
        ),
        migrations.AddField(
            model_name='workout',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='coach.workoutplan'),
        ),
    ]
