# Generated by Django 4.2.13 on 2026-06-19 19:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gym_user', '0006_conversation_created_by_conversation_is_group_and_more'),
        ('coach', '0003_coach_bio_coach_specialty_coach_years_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutplan',
            options={'ordering': ['plan_name']},
        ),
        migrations.AddField(
            model_name='exercise',
            name='rest_seconds',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='exercise',
            name='sets',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='exercise',
            name='video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='duration_weeks',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='target_goal',
            field=models.CharField(choices=[('general', 'General Fitness'), ('weight_loss', 'Weight Loss'), ('strength', 'Strength'), ('endurance', 'Endurance'), ('mobility', 'Mobility')], default='general', max_length=40),
        ),
        migrations.AlterField(
            model_name='professionalfeedback',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='AssignedWorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='assigned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_assignments', to='coach.coach')),
                ('gym_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_workout_plans', to='gym_user.gymuser')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='coach.workoutplan')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('plan', 'gym_user')},
            },
        ),
    ]
