# Generated by Django 6.0.4 on 2026-06-18 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('gym_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthAdvisor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('advisor_name', models.CharField(max_length=255)),
                ('assigned_users', models.ManyToManyField(blank=True, related_name='health_advisors', to='gym_user.gymuser')),
            ],
        ),
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('diet_plan', models.TextField(blank=True, help_text='Diet plan details / notes')),
                ('notes', models.TextField(blank=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='health_advisor.healthadvisor')),
                ('gym_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_reports', to='gym_user.gymuser')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('advice', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='health_advisor.healthadvisor')),
                ('gym_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='gym_user.gymuser')),
            ],
        ),
    ]
