# Generated by Django 4.2.13 on 2026-06-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_advisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthadvisor',
            name='bio',
            field=models.TextField(blank=True, help_text='Short public bio shown to prospective gym users.'),
        ),
        migrations.AddField(
            model_name='healthadvisor',
            name='specialty',
            field=models.CharField(blank=True, help_text='Public specialty shown on the Meet Our Health Advisors section.', max_length=120),
        ),
        migrations.AddField(
            model_name='healthadvisor',
            name='years_experience',
            field=models.PositiveIntegerField(blank=True, help_text='Optional years of health advisory experience for the public team card.', null=True),
        ),
    ]
