# Generated by Django 4.2.13 on 2026-06-19 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_user', '0006_conversation_created_by_conversation_is_group_and_more'),
        ('health_advisor', '0004_alter_recommendation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='status',
            field=models.CharField(choices=[('sent', 'Unread'), ('read', 'Read'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='sent', max_length=20),
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('target_goal', models.CharField(blank=True, max_length=160)),
                ('daily_calorie_target', models.PositiveIntegerField(blank=True, null=True)),
                ('meal_notes', models.TextField(blank=True)),
                ('restrictions_allergies', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to='health_advisor.healthadvisor')),
                ('gym_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to='gym_user.gymuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
