# Generated by Django 6.0.4 on 2026-06-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_user', '0008_monthlyworkoutschedule'),
        ('health_advisor', '0005_recommendation_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietplan',
            name='gym_user',
        ),
        migrations.AddField(
            model_name='dietplan',
            name='gym_users',
            field=models.ManyToManyField(blank=True, related_name='diet_plans', to='gym_user.gymuser'),
        ),
    ]
