# Generated by ChatGPT for Django 4.2 compatibility

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
        ('health_advisor', '0001_initial'),
        ('gym_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymuser',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gymuser',
            name='assigned_coach',
            field=models.ForeignKey(
                blank=True,
                help_text='Fitness coach assigned by admin.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assigned_gym_users',
                to='coach.coach',
            ),
        ),
        migrations.AddField(
            model_name='gymuser',
            name='assigned_advisor',
            field=models.ForeignKey(
                blank=True,
                help_text='Health advisor assigned by admin.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assigned_gym_users',
                to='health_advisor.healthadvisor',
            ),
        ),
    ]
