# Generated by ChatGPT for Django 4.2 compatibility

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_initial'),
        ('gym_user', '0002_assignments_profile_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='coach.workoutplan'),
        ),
    ]
