# Generated by Django 4.2.13 on 2026-06-19 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_existing_conversations(apps, schema_editor):
    GymUser = apps.get_model('gym_user', 'GymUser')
    Conversation = apps.get_model('gym_user', 'Conversation')
    for gym_user in GymUser.objects.exclude(assigned_coach=None).exclude(assigned_advisor=None):
        Conversation.objects.get_or_create(
            gym_user=gym_user,
            defaults={
                'coach_id': gym_user.assigned_coach_id,
                'health_advisor_id': gym_user.assigned_advisor_id,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_initial'),
        ('health_advisor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym_user', '0003_alter_activitylog_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='coach.coach')),
                ('gym_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='gym_user.gymuser')),
                ('health_advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='health_advisor.healthadvisor')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('attachment_url', models.URLField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='gym_user.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RunPython(create_existing_conversations, migrations.RunPython.noop),
    ]
