# Generated by Django 4.2.13 on 2026-06-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_user', '0006_conversation_created_by_conversation_is_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_opened',
            field=models.BooleanField(default=False),
        ),
    ]
