# Generated by Django 4.2.13 on 2026-06-19 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_user', '0007_notification_is_opened'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyWorkoutSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_schedules', to='gym_user.gymuser')),
            ],
            options={
                'ordering': ['date', 'time', 'title'],
            },
        ),
    ]
