# Generated by ChatGPT for Django 4.2 compatibility

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_username'),
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='event',
            field=models.CharField(
                choices=[
                    ('user_created', 'User Created'),
                    ('user_deleted', 'User Deleted'),
                    ('status_changed', 'Status Changed'),
                    ('assignment_updated', 'Assignment Updated'),
                    ('login', 'Login'),
                    ('faq_updated', 'FAQ Updated'),
                    ('feedback_updated', 'Feedback Updated'),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name='LoginActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(blank=True, max_length=20)),
                ('login_timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('successful', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Login activities',
                'ordering': ['-login_timestamp'],
            },
        ),
    ]
