# Generated by Django 4.2.13 on 2026-06-21 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_feedback_options_remove_feedback_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='feedback_attachments/'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('bug_report', 'Report Bug'), ('feature_request', 'Feature Request'), ('user_report', 'Report User'), ('account_issue', 'Account Issue'), ('system_performance', 'System Performance'), ('general_inquiry', 'General Inquiry'), ('other', 'Other')], default='general_inquiry', max_length=30),
        ),
        migrations.AddField(
            model_name='feedback',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
